require('plugins')
require('general')
require('mappings')
require('lua-treesitter')
require('lua-tree')
require('lua-lspconfig')
require('lua-compe')
require('lua-telescope')
require('lua-icons')
require('lua-barbar')
require('lua-galaxyline')
require('lua-commenter')
require('lua-git')
require('lua-colorizer')
vim.cmd [[set background=dark]]
vim.cmd("hi Normal guibg=NONE ctermbg=NONE")
