require('plugins/treesitter')
require('plugins/commenter')
require('plugins/galaxyline')
require('plugins/telescope')
require('plugins/lspkind')
require('plugins/gitsigns')
require('plugins/nvimtree')
require('nvim-ts-autotag').setup()
require('colorizer').setup()

require('lsp/install')
require('lsp/config')
require('lsp/compe')
require('lsp/efm')
require('lsp/tsserver')
require('lsp/graphql')
require('lsp/html')
require('lsp/css')
require('lsp/lua')
require('lsp/rust')
require('lsp/prisma')
require('lsp/metal')

