require('plugins/treesitter')
require('plugins/galaxyline')
require('plugins/bufferline')
require('plugins/telescope')
require('plugins/lspkind')
require('plugins/gitsigns')
require('plugins/nvimtree')

require('colorizer').setup()

require('lsp/cmp')
require('plugins/pairs')
require('lsp/efm')
require('lsp/tsserver')
require('lsp/graphql')
require('lsp/go')
require('lsp/c')
require('lsp/json')
require('lsp/yaml')
require('lsp/html')
require('lsp/css')
require('lsp/tailwindcss')
require('lsp/lua')
